import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";
import "./globals.css";
import { Inter, Sora } from "next/font/google";

const inter = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
